name: IslandSystem
version: 3.0.0
author: Hakuyamu
api-version: 1.17
main: de.leonheuer.skycave.islandsystem.IslandSystem
depend:
  - WorldEdit
  - WorldGuard

commands:
  sbadmin:
    description: sbadmin command
    permission: skycave.islands.command
    permission-message: "§8❙ §fSky§6Bee§fIsland §8» §cDu hast keine Rechte für diesen Befehl."
  sb:
    description: sb command

permissions:
  skycave.islands.command:
    description: command permission
  skycave.islands.alert:
    description: alert permission