name: IslandSystem
version: 1.0.2
author: Hakuyamu
api-version: 1.18
main: de.leonheuer.skycave.islandsystem.IslandSystem
depend: [ WorldEdit, WorldGuard, Multiverse-Core ]

commands:
  sbadmin:
    permission: skycave.islands.command
  sb:
    description: sb command

permissions:
  skycave.islands:
    children:
      - command
      - alert